# Exercise Project 1 

Dataset: [NYC Housing Prices](https://www.kaggle.com/datasets/ishank2005/nyc-housing-prices-csv)

|Step|Description|
|---|---|
|1| Clean the data|
|2| Define the x and y variables.|
|3| Train/test splitting|
|4| Model Initialization|
|5| Obtain the intercept|
|6| Retrieve test predictions|
|7| Determine if prediction line is linear|
|8| Test result|
|9| Obtain error metrics|
|10| Plotting prediction to the distribution|
|11| Plotting linplot indepedently|

---

### Code

In [2]:
# import 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics

# Reading the dataframe and storing it.
df = pd.read_csv("datasets/nyc_housing.csv")

# Initial look
df.head(3)

##### Data Prep/Cleaning

In [9]:
df.head(5)

,borough_x,block,lot,sale_price,zip_code,borough_y,yearbuilt,lotarea,bldgarea,resarea,comarea,unitsres,unitstotal,numfloors,latitude,longitude,landuse,bldgclass,building_age
0,1,400,11,280000,10009.0,MN,1900.0,2404.0,6875.0,6875.0,0.0,18.0,18.0,5.0,40.724415,-73.983891,2.0,C6,125.0
1,1,402,36,2000000,10009.0,MN,1900.0,1919.0,7810.0,6810.0,1000.0,8.0,10.0,5.0,40.724975,-73.981535,2.0,C4,125.0
2,1,402,60,3400000,10009.0,MN,1920.0,2150.0,6152.0,5352.0,800.0,8.0,9.0,5.0,40.725346,-73.983112,4.0,C7,105.0
3,1,404,42,4000000,10009.0,MN,1855.0,2369.0,6990.0,6990.0,0.0,10.0,10.0,5.0,40.727398,-73.980600,2.0,C4,170.0
4,1,372,55,655000,10009.0,MN,1920.0,5298.0,17990.0,17990.0,0.0,20.0,20.0,5.0,40.720621,-73.979534,2.0,C6,105.0

In [13]:
# Let's first get rid of a few columns which aren't going to be very useful
df = df.drop(["borough_x","latitude","longitude","landuse","bldgclass"], axis=1)
df

,block,lot,sale_price,zip_code,borough_y,yearbuilt,lotarea,bldgarea,resarea,comarea,unitsres,unitstotal,numfloors,building_age
0,400,11,280000,10009.0,MN,1900.0,2404.0,6875.0,6875.0,0.0,18.0,18.0,5.0,125.0
1,402,36,2000000,10009.0,MN,1900.0,1919.0,7810.0,6810.0,1000.0,8.0,10.0,5.0,125.0
2,402,60,3400000,10009.0,MN,1920.0,2150.0,6152.0,5352.0,800.0,8.0,9.0,5.0,105.0
3,404,42,4000000,10009.0,MN,1855.0,2369.0,6990.0,6990.0,0.0,10.0,10.0,5.0,170.0
4,372,55,655000,10009.0,MN,1920.0,5298.0,17990.0,17990.0,0.0,20.0,20.0,5.0,105.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34434,7316,4,850000,10309.0,SI,1996.0,3180.0,1300.0,1300.0,0.0,2.0,2.0,2.0,29.0
34435,7317,130,855000,10309.0,SI,1995.0,3700.0,2500.0,2500.0,0.0,2.0,2.0,3.0,30.0
34436,7359,3,1200000,10309.0,SI,2001.0,4359.0,2200.0,2200.0,0.0,2.0,2.0,2.0,24.0
34437,6998,6,800000,10309.0,QN,1950.0,2185.0,1458.0,1458.0,0.0,1.0,1.0,2.0,75.0
34438,7267,81,999999,10309.0,SI,1999.0,6135.0,3750.0,0.0,3750.0,0.0,3.0,2.0,26.0